# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93c7cd9dcc48e0ce5ac473077b45b985"
name = "ECS Announcement"
application_url = "https://ecs-announcement-app-dev-web-live.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://ecs-announcement-app-dev-backend-live.onrender.com/api/shopify/webhook"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [ 
  "https://ecs-announcement-app-dev-web-live.onrender.com/auth/callback",
  "https://ecs-announcement-app-dev-web-live.onrender.com/auth/shopify/callback",
  "https://ecs-announcement-app-dev-web-live.onrender.com/api/auth/callback"
  ]
